# Generated by Django 4.2.1 on 2023-07-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_payment_method_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_by',
            field=models.CharField(default='', max_length=100, verbose_name='Person who ordered'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Payment amount'),
        ),
    ]
