# Generated by Django 4.2.1 on 2023-07-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_ordered_by_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_by',
            field=models.CharField(default='---', max_length=100, verbose_name='Person who ordered'),
        ),
    ]
