# Generated by Django 4.2.1 on 2023-07-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_payment_method_alter_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price_cost',
            field=models.IntegerField(default=0, verbose_name='Product cost Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_sell',
            field=models.IntegerField(default=0, verbose_name='Product sell Price'),
        ),
    ]
