# Generated by Django 4.2.3 on 2023-07-13 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_product_order_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Order',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Product',
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.order', verbose_name='Corresponding Order'),
        ),
    ]
