# Generated by Django 4.2.3 on 2023-07-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_order_payment_order_remove_order_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(default=None, to='core.product', verbose_name="Order's Products"),
        ),
    ]
