# Generated by Django 4.2.3 on 2023-07-13 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='order',
            new_name='Order',
        ),
    ]
