# Generated by Django 4.2.3 on 2023-07-13 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_rename_order_transaction_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Order',
            new_name='order',
        ),
    ]
